recipeapp/recipes/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, SubmitField, TextAreaField, SelectField
from wtforms.validators import DataRequired


class RecipeForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    ingredients = TextAreaField('Ingredients', validators=[DataRequired()])
    directions = TextAreaField('Directions', validators=[DataRequired()])
    course = SelectField('Course', choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('drink', 'Drink'), ('snack', 'Snack')], validators=[DataRequired()])
    notes = TextAreaField('Notes:')
    picture = FileField('Add A Recipe Picture?', validators=[FileAllowed(['jpg', 'png'])])
    submit = SubmitField('Submit')

recipeapp/recipes/routes.py
import os
import secrets
from flask import render_template, url_for, flash, redirect, request, Blueprint, abort, current_app
from recipeapp import db
from recipeapp.models import Recipe
from flask_login import current_user, login_required
from recipeapp.recipes.forms import RecipeForm

recipes = Blueprint('recipes', __name__)


@recipes.route('/add_recipe', methods=['GET', 'POST'])
@login_required
def add_recipe():
    form = RecipeForm()
    if form.validate_on_submit():
        if form.picture.data:
            print("Getting Picture")
            photo_file = upload_photo(form.picture.data)
            recipe = Recipe(title=form.title.data, ingredients=form.ingredients.data, directions=form.directions.data, author=current_user, course=form.course.data, notes=form.notes.data, recipe_image=photo_file)
        else:
            recipe = Recipe(title=form.title.data, ingredients=form.ingredients.data, directions=form.directions.data, author=current_user, course=form.course.data, notes=form.notes.data)
        db.session.add(recipe)
        db.session.commit()
        flash(f'{ recipe.title } Added', 'success')
        return redirect(url_for('main.home'))
    return render_template('new_recipe.html', title='A Recipe', form=form, legend="New Recipe")


@recipes.route('/recipe/<int:recipe_id>/')
def recipe(recipe_id):
    recipe = Recipe.query.get_or_404(recipe_id)
    if recipe.recipe_image:
        image_file = url_for('static', filename='recipe_pics/' + recipe.recipe_image)
        return render_template('recipe.html', recipe=recipe, title=recipe.title, image_file=image_file)
    else:
        return render_template('recipe.html', recipe=recipe, title=recipe.title)


@recipes.route('/recipes/<string:course>/', methods=['GET'])
def recipes_course(course):
    recipes = Recipe.query.filter_by(course=course)
    return render_template('recipes.html', recipes=recipes)


@recipes.route('/recipes/search/<string:title>/', methods=['GET', 'POST'])
def recipes_search(title):
    recipes = Recipe.query.filter(Recipe.title.ilike(f"%{title}%"))
    return render_template('recipes.html', recipes=recipes)


@recipes.route('/recipes/search/', methods=['GET', 'POST'])
def recipes_searchb():
    search_text = request.form['search']
    recipes = Recipe.query.filter(Recipe.title.ilike(f"%{search_text}%"))
    return render_template('recipes.html', recipes=recipes)


@recipes.route('/recipe/<int:recipe_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_recipe(recipe_id):
    recipe = Recipe.query.get_or_404(recipe_id)
    if recipe.author != current_user:
        abort(403)
    form = RecipeForm()
    if form.validate_on_submit():
        print("form here")
        if form.picture.data:
            print("Getting Picture")
            photo_file = upload_photo(form.picture.data)
            recipe.recipe_image = photo_file
        recipe.title = form.title.data
        recipe.ingredients = form.ingredients.data
        recipe.directions = form.directions.data
        recipe.course = form.course.data
        recipe.notes = form.notes.data
        db.session.commit()
        flash('Recipe Updated!', 'success')
        return redirect(url_for('recipes.recipe', recipe_id=recipe.id))
    elif request.method == 'GET':
        form.title.data = recipe.title
        form.ingredients.data = recipe.ingredients
        form.directions.data = recipe.directions
        form.course.data = recipe.course
        form.notes.data = recipe.notes
    return render_template('new_recipe.html', title='Edit Recipe', form=form, legend="Edit Recipe")


@recipes.route('/recipe/<int:recipe_id>/delete', methods=['POST'])
@login_required
def delete_recipe(recipe_id):
    recipe = Recipe.query.get_or_404(recipe_id)
    if recipe.author != current_user:
        abort(403)
    db.session.delete(recipe)
    db.session.commit()
    flash(f"{ recipe.title } Deleted", 'success')
    return redirect(url_for('main.home'))


def upload_photo(picture_in):
    random_filename = secrets.token_hex(8)
    _, f_ext = os.path.splitext(picture_in.filename)
    final_pic = random_filename + f_ext
    picture_path = os.path.join(current_app.root_path, 'static/recipe_pics', final_pic)
    picture_in.save(picture_path)

    return final_pic

recipeapp/users/routes.py
from flask import render_template, url_for, flash, redirect, Blueprint
from flask_login import login_user, current_user, logout_user
from recipeapp import db, bcrypt
from recipeapp.models import User
from recipeapp.users.forms import RegistrationForm, LoginForm

users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data.lower(), password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Account created - You are now logged in to browse or add recipes', 'success')
        login_user(user)
        return redirect(url_for('main.home'))
    return render_template('register.html', title='Register', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            return redirect(url_for('main.home'))
        else:
            flash('Login Unsuccesful, Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('users.login'))

recipeapp/templates/home.html
{% extends "layout.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-8 text-center order-2 order-sm-1">
            <div>
                <img style='height: 100%; width: 100%; object-fit: contain; margin-bottom: 15px; padding: 15px' src="{{ url_for('static', filename='recipe_pics/recipe_home.jpg') }}">
            </div>
            <h2 class="text-center" style="margin: 20px; margin-bottom: 30px"> Latest Recipes:</h2>
        {% for recipe in recipes[:5] %}
        <article class="text-center recipe-heading">
            <h2 class="text-center"><a class="article-title" href="{{ url_for('recipes.recipe', recipe_id=recipe.id) }}">{{ recipe.title }}</a></h2>
        </article>
        {% endfor %}
        </div>
        <div class="col-md-4 text-center order-1 order-sm-2">
            <form action="{{ url_for('recipes.recipes_searchb') }}" method="POST">
                <input class="form-control active-purple-4 active-purple-3 mb-4" type="text/submit" placeholder="Search" aria-label="Search" name="search">
            </form>
            <div class="content-section">
                <h3>Courses</h3>
                <p class='text-muted' id='testclass'>Browse Recipes by Course.
                    <ul class="list-group">
                        <li class="list-group-item list-group-item-light"><a
                                href="{{ url_for('recipes.recipes_course', course='breakfast') }}">Breakfast</a></li>
                        <li class="list-group-item list-group-item-light"><a
                                href="{{ url_for('recipes.recipes_course', course='lunch') }}">Lunch</a></li>
                        <li class="list-group-item list-group-item-light"><a
                                href="{{ url_for('recipes.recipes_course', course='dinner') }}">Dinner</a></li>
                        <li class="list-group-item list-group-item-light"><a
                                href="{{ url_for('recipes.recipes_course', course='drink') }}">Drinks</a></li>
                        <li class="list-group-item list-group-item-light"><a
                                href="{{ url_for('recipes.recipes_course', course='snack') }}">Snacks</a></li>
                    </ul>
                </p>
            </div>
        </div>
    </div>
{% endblock content%}

recipeapp/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">

    {% if title %}
    <title>Recipe Haven - {{ title }}</title>
    {% else %}
    <title>Recipe Haven</title>
    {% endif %}
</head>

<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="/">Recipe Haven</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                    </div>
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav">
                        {% if current_user.is_authenticated %}
                            <a class="nav-item nav-link" href="{{ url_for('recipes.add_recipe') }}">New Recipe</a>
                            <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                        {% else %}
                            <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                            <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </header>

    <main role="main" class="container">
            <div class="col-md-8">
                {% with messages= get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }}">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
            </div>
                {% block content %}{% endblock %}
    </main>


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    <script src="//cdn.ckeditor.com/4.11.4/basic/ckeditor.js"></script>
    <script type="text/javascript">
        CKEDITOR.replace('editor')
    </script>
    <script type="text/javascript">
        CKEDITOR.replace('editor2')
    </script>
    <script type="text/javascript">
        CKEDITOR.replace('editor3')
    </script>
</body>

</html>

recipeapp/templates/login.html
{% extends "layout.html" %}

{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Log In</legend>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control form control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                    {{ form.password(class="form-control form control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-check">
                {{ form.remember(class="form.check.input") }}
                {{ form.remember.label(class="form.check.label") }}
            </div>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </fieldset>
    </form>
</div>
<div class="border-top pt-3">
    <small class="text-muted">
        Not Registered? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
    </small>
</div>

{% endblock content %}

recipeapp/templates/new_recipe.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="row">
            <div class="form-group col-md-3">
                {{ form.course.label(class="form-control-label") }}
                {% if form.course.errors %}
                    {{ form.course(class="form-control form-control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.course.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.course(class="form-control form-control-sm") }}
                {% endif %}
            </div>
            </div>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.ingredients.label(class="form-control-label") }}
                {% if form.ingredients.errors %}
                    {{ form.ingredients(class="form-control form control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.ingredients.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.ingredients(class="form-control form-control-lg", id="editor") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.directions.label(class="form-control-label") }}
                {% if form.directions.errors %}
                    {{ form.directions(class="form-control form control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.directions.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.directions(class="form-control form-control-lg", id="editor2") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.notes.label(class="form-control-label") }}
                {% if form.notes.errors %}
                    {{ form.notes(class="form-control form control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.notes.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.notes(class="form-control form-control-lg", id="editor3") }}
                {% endif %}
            </div>
        <div class="form-group">
            {{ form.picture.label() }}
            {{ form.picture(class="form-control-file") }}
            {% if form.picture.errors %}
                {% for error in form.picture.errors %}
                    <span class="text-danger">{{ error }}</span></br>
                {% endfor %}
            {% endif %}
        </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content%}

recipeapp/templates/recipe.html
{% extends "layout.html" %}

{% block content %}

    <h1 class="recipe-page-heading">{{ recipe.title }}</h1>
    {% if recipe.recipe_image %}
        <div class="row">
            <div class="col-md-4">
                <div>
                    <img src="{{ image_file }}" style="width: 100%; height: 100%; padding: 20px">
                </div>
            </div>
        </div>
    {% endif %}
    <div class="row">
        <div class="col-md-4">
            <div class="ingredients">
                <h2>Ingredients</h2>
                <p>{{ recipe.ingredients | safe }}</p>
            </div>
        </div>
        <div class="col-md-8">
            <div class="ingredients">
                <h2>Directions</h2>
                <p>{{ recipe.directions | safe }}</p>
            </div>
        </div>
    </div>
    {% if recipe.notes %}
        <div class="ingredients">
            <h2>Notes:</h2>
            <p>{{ recipe.notes | safe }}</p>
        </div>
    {% endif %}
        </div>
    {% if recipe.author == current_user %}
        <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('recipes.edit_recipe', recipe_id=recipe.id) }}">Edit Recipe</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
    {% endif %}

    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Are You Sure?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <form action="{{ url_for('recipes.delete_recipe', recipe_id = recipe.id) }}" method="POST">
                        <input type="submit" class="btn btn-danger" value="Delete">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content%}

recipeapp/templates/recipes.html
{% extends "layout.html" %}

{% block content %}
<div class="row">
    <div class="col-md-8 text-center order-2 order-sm-1">
        {% for recipe in recipes %}
            <article class="text-center recipe-heading">
                <h2 class="text-center"><a class="article-title"
                        href="{{ url_for('recipes.recipe', recipe_id=recipe.id) }}">{{ recipe.title }}</a></h2>
            </article>
        {% endfor %}
    </div>
    <div class="col-md-4 text-center order-1 order-sm-2">
        <form action="{{ url_for('recipes.recipes_searchb') }}" method="POST">
            <input class="form-control active-purple-4 active-purple-3 mb-4" type="text/submit" placeholder="Search"
                aria-label="Search" name="search">
        </form>
        <div class="content-section">
            <h3>Courses</h3>
            <p class='text-muted' id='testclass'>Browse Recipes by Course.
                <ul class="list-group">
                    <li class="list-group-item list-group-item-light"><a
                            href="{{ url_for('recipes.recipes_course', course='breakfast') }}">Breakfast</a></li>
                    <li class="list-group-item list-group-item-light"><a
                            href="{{ url_for('recipes.recipes_course', course='lunch') }}">Lunch</a></li>
                    <li class="list-group-item list-group-item-light"><a
                            href="{{ url_for('recipes.recipes_course', course='dinner') }}">Dinner</a></li>
                    <li class="list-group-item list-group-item-light"><a
                            href="{{ url_for('recipes.recipes_course', course='drink') }}">Drinks</a></li>
                    <li class="list-group-item list-group-item-light"><a
                            href="{{ url_for('recipes.recipes_course', course='snack') }}">Snacks</a></li>
                </ul>
            </p>
        </div>
    </div>
</div>
{% endblock content%}

recipeapp/templates/register.html
{% extends "layout.html" %}

{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Join Today</legend>
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}
                {% if form.username.errors %}
                    {{ form.username(class="form-control form control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.username(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control form control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                    {{ form.password(class="form-control form control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label") }}
                {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class="form-control form control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.confirm_password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.confirm_password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
<div class="border-top pt-3">
    <small class="text-muted">
        Already Have An Account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign In</a>
    </small>
</div>


{% endblock content %}